export const posts = [
  {
    id: 1,
    src: '/imgs/cover.png',
    alt: 'img',
    title: 'test1',
    summary: 'test1 sdiohfdsiohf sdajlfsdolajfdsao dsiuhfgidsuhf sdof hdsh odshfdsohfdosahf',
    date: '2024-12-30',
  },
  {
    id: 2,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '探索Web3.0的未来',
    summary: '随着区块链技术的发展，Web3.0正在重塑互联网的未来。本文将深入探讨去中心化应用的潜力和挑战。',
    date: '2024-11-15',
  },
  {
    id: 3,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '人工智能在医疗领域的应用',
    summary: 'AI技术正在革新医疗诊断和治疗方案。从图像识别到预测分析，AI正在帮助医生做出更准确的决策。',
    date: '2024-10-20',
  },
  {
    id: 4,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '可持续发展与绿色科技',
    summary: '面对气候变化，科技如何助力环保？本文分析最新的环保科技发展趋势和实际应用案例。',
    date: '2024-09-05',
  },
  {
    id: 5,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '5G时代的物联网革命',
    summary: '5G网络的普及为物联网带来了新的可能。从智能家居到工业互联网，万物互联正在成为现实。',
    date: '2024-08-18',
  },
  {
    id: 6,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '量子计算：下一代计算革命',
    summary: '量子计算机可能彻底改变计算领域。本文探讨其原理、最新进展及潜在应用场景。',
    date: '2024-07-22',
  },
  {
    id: 7,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '元宇宙与虚拟现实',
    summary: '元宇宙概念持续升温，VR/AR技术不断突破。来看看这个虚拟世界带来的新机遇。',
    date: '2024-06-30',
  },
  {
    id: 8,
    src: '/imgs/cover.png',
    alt: 'img',
    title: '区块链与金融创新',
    summary: '从比特币到DeFi，区块链技术正在重构金融服务。探索数字货币和去中心化金融的发展。',
    date: '2024-05-15',
  },
]
